### ISSUE TITLE
bibliography style

### ISSUE THREAD

**Issue by AtomicNess123** [andras-simonyi/citeproc-orgref#14]
Thanks for this package, first of all! Much needed.

Do I understand that having these lines:
```
bibliographystyle:apa
bibliography:library.bib
```

is not enough for rendering correctly the bibliography and I must add `#+CSL_STYLE: /path/to/csl_style-APA` in the buffer (in addition or instead of bibliographystyle:apa)?

Thanks for the clarification.

**Comment by andras-simonyi** [comment]
Yes, if you want to use a different style from the default Chicago then you have to have #+CSL_STYLE: /path/to/csl_style-APA  in your Org file -- bibliographystyle:apa has no effect on citeproc-org.
