### ISSUE TITLE
Snag : How to use more than one bib file ?

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [andras-simonyi/citeproc-orgref#19]
I wanted to use more than one bibliography file for my references : for professional reasons, my reference database, maintained in Zotero, is humongous (about 15000 references today), and I export small parts of this database via BetterBibtex to `.bib` files.

The `org ref`'s author [suggests](https://kitchingroup.cheme.cmu.edu/blog/2014/05/13/Using-org-ref-for-citations-and-references/#sec-2) to mention them in the same bibliography link, separated by commas. This fails with `citeproc` : 
```
[[bibliography:Modernes.bib,Antiques.bib]]
```
gives me the message : 
```
Opening input file: Aucun fichier ou dossier de ce type, /home/charpent/Temporaire/Org-mode/Refs/Modernes.bib,Antiques.bib
```

I also tried : 
```
[[bibliography:Modernes.bib]]
[[bibliography:Antiques.bib]]
```
which failed on the first reference to a citation in `Antiques.bib` : 
```
citeproc-render-bib: Wrong type argument: listp, "NO_ITEM_DATA:Bayes:63"
```
Similar results when I invert the order of the links, *i. e.* failure at the first reference to a citation in `Modernes.bib`.

I'm stuck, with a use case I do not think exceptional...

**EDIT :** I forgot to specify that working with a single link to a concatenation of the files works, obviously...

**Comment by andras-simonyi** [comment]
Hi, thanks for the report! If I remember correctly this is not yet supported but very easy to add -- will do it shortly.

**Comment by mohkale** [comment]
I've just started trying to render my org-roam brain through ox-hugo and this is something I'm missing. Is there anything I can do to help @andras-simonyi?

**Comment by EmmanuelCharpentier** [comment]
BTW : won't this be obsoleted by the upcoming `org-cite` system ? Nicolas Gaziou has built `org-cite-csl.el` around `citeproc.el`, with impressive (but not perfect) results (see [this new issue](https://github.com/andras-simonyi/citeproc-el/issues/32) against the latter).

**Comment by andras-simonyi** [comment]
Hello, sorry for responding only now. I've posted a general note on the status of citeproc-org in the light of the recent developments in org-cite and `oc-csl` (which is in many ways a [friendly] fork of citeproc-org ). As regarding this particular issue, it should be fixed in the new `org_cite_backports` branch: now one can have a comma separated list (without spaces) of bib files in the bibliography link. I'd appreciate your feedback if you give it a try.

**Comment by andras-simonyi** [comment]
Because of the implemented fix and in the absence of activity I'm closing this issue.
