### ISSUE TITLE
Respect org-ref-default-bibliography

### ISSUE THREAD

**Issue by dcherian** [andras-simonyi/citeproc-orgref#2]
When `bibliography:` is not present, `citeproc-org` should use the value in `org-ref-default-bibliography`

**Comment by andras-simonyi** [comment]
Thanks! The reason why this is not already in the code is that the bibliography link has two roles, specifying the bibliography file to use _and_ the location where the bibliography should be placed. Do you think citeproc-org should simply place the bibliography at the end of the document if the bibliography link is missing but `org-ref-default-bibliography` is set? (Another option would be to omit the bibliography and render only the citations...)

**Comment by dcherian** [comment]
Yes placing it at the end would be a good default

**Comment by dcherian** [comment]
This would also take care of the case where only `bibliography: here` is specified in the document?

**Comment by andras-simonyi** [comment]
I've pushed some changes to the master branch which should take care of missing bibliography links and links with "here" as the target. Note that the value of `org-ref-default-bibliography` is a list, but `citeproc-el` currently works only with single bibliography files so the first file in the list is used.

**Comment by dcherian** [comment]
Sounds good. I'll test it tomorrow. Thanks!
