### ISSUE TITLE
Discrepancies with Zotero in how citations are rendered

### ISSUE THREAD

**Issue by benthamite** [andras-simonyi/citeproc-orgref#20]
Thank you for creating this package. I thought I'd have to resign myself to using an external application to cite works that required the use of a particular citation format, and I'm pretty excited to see that I may be able to do this without leaving Emacs!

Unfortunately, there are some significant discrepancies in how `citeproc-org` renders citations and how other citation-management tools, such as Zotero, render them. Moreover, it is the latter that conform to the specifications provided in the relevant csl file. Here is an example.

<details><summary>org buffer</summary>
<p>

```
#+CSL_STYLE: /Users/pablostafforini/Dropbox/org/bibliography/glossa.csl

cite:Williamson2005KnowledgeScepticisma

[[bibliography:/Users/pablostafforini/Dropbox/org/bibliography/new.bib]]
```

</p>
</details>

<details><summary>new.bib</summary>
<p>

```
@incollection{Williamson2005KnowledgeScepticisma,
  title = {Knowledge and Scepticism},
  booktitle = {The Oxford Handbook of Contemporary Philosophy},
  author = {Williamson, Timothy},
  editor = {Jackson, Frank and Smith, Michael},
  date = {2005},
  publisher = {Oxford University Press},
  location = {Oxford},
  doi = {10.1093/oxfordhb/9780199234769.003.0023},
  url = {http://oxfordhandbooks.com/view/10.1093/oxfordhb/9780199234769.001.0001/oxfordhb-9780199234769-e-23},
  urldate = {2021-07-19},
  abstract = {The Oxford Handbook of Contemporary Philosophy is the definitive guide to what is happening in the lively and fascinating subject of contemporary philosophy. More than thirty distinguished scholars contribute incisive and up-to-date critical surveys of the principal areas of research into this subject. The coverage is broad, with sections devoted to moral philosophy, social and political philosophy, philosophy of mind and action, philosophy of language, metaphysics, epistemology, and philosophy of the sciences.},
  zotero = {R2Q9V8HZ}
}
```

</p>
</details>

<details><summary>citeproc-org</summary>
<p>

Williamson, Timothy. Knowledge and Scepticism. In Frank Jackson & Michael Smith (eds.), The Oxford Handbook of Contemporary Philosophy,. Oxford: Oxford University Press. Retrieved from http://oxfordhandbooks.com/view/10.1093/oxfordhb/9780199234769.001.0001/oxfordhb-9780199234769-e-23

</p>
</details>

<details><summary>Zotero</summary>
<p>

Williamson, Timothy. 2005. Knowledge and scepticism. In Frank Jackson & Michael Smith (eds.), The Oxford Handbook of Contemporary Philosophy,. Oxford: Oxford University Press. DOI: https://doi.org/10.1093/oxfordhb/9780199234769.003.0023

</p>
</details>

[glossa.csl](https://raw.githubusercontent.com/citation-style-language/styles/master/glossa.csl)

As you can see, `citeproc-org` is omitting the date, and appending the contents of the `url` field rather than the `doi` field. Do you happen to know what might be going on?

**Comment by andras-simonyi** [comment]
Hello, thanks for the report! As for omitting the date, the problem is that `date` is not a valid BibTeX field (it's biblatex, which is unsupported at the moment), if it's replaced with the correct `year` then this problem is fixed. Interestingly enough, I cannot reproduce the DOI vs URL problem, with the latest `citeproc-el`  I get the same DOI rendering as Zotero's. 

A general remark: there are huge changes in Org's citation support right now, the branch with built-in native citation elements and supporting infrastructure for export, insertion, fontification has just been merged into Org's master a week ago, and will be part of the next official release. Accordingly, `citeproc-org` will soon be switched to maintenance mode and the main focus will shift to improving Org's built-in CSL support.

**Comment by benthamite** [comment]
Thanks for the quick and informative reply! In light of your general remark, I think I'll try to familiarize myself with the recent developments with org's citation support and wait a bit to see how `org-ref` and `biblatex-completion` adapt to it.
