### ISSUE TITLE
referencing previous footnotes

### ISSUE THREAD

**Issue by ertwro** [andras-simonyi/citeproc-orgref#6]
Not really an issue but I have a question. I've been trying to do something like this for almost a year with org-ref:
```
----------------------------------------
82. Id. at 1194–95.
83. Id. at 1197.
84. Id.
85. As a result of negotiations with Senate Judiciary Committee member Patrick Leahy,
section 216 of the PATRIOT Act excludes Pen/Traps from collecting “the contents of any
wire or electronic communications.” Id. at 1198.
86. See 18 U.S.C. § 2518 (2012) (providing a procedure for interception of wire, oral, or
electronic communications). The term “super” warrant is often used colloquially to describe
Wiretap Act procedures because of application requirements such as “a full and complete
statement as to whether or not other investigative procedures have been tried and failed or
why they reasonably appear to be unlikely to succeed if tried or to be too dangerous.” Id.
87. See Howell, supra note 81, at 1197.
88. See infra Section IV.C for an explanation of Uniform Resource Locators (URLs).
89. Howell, supra note 81, at 1197 (citing Letter from Daniel A. Bryant, Assistant Attorney General, to Patrick J. Leahy, Chairman, Committee on the Judiciary (Nov. 29, 2001)).
The DOJ further noted that “a file path identifying the location of a requested document
may ‘at a certain point along a URL . . . become too specific to be appropriately collected by
a Pen/Trap order.’” Id.
90. 18 U.S.C. § 3127(3) (2012) (defining pen register as “a device or process which records or decodes dialing, routing, addressing, and signaling information transmitted by an
```
I was wondering if there's a way to reference previous footnotes, (I do cross-references with the  radio-button package) but I wanna keep macros in order to export to docx files, since in peer review law docx files are almost obligatory.

**Comment by andras-simonyi** [comment]
Hello, unfortunately I'm not familiar with legal reference systems. What I know is that at the moment the citeproc-el library  which citeproc-org uses to format references supports only CSL 1.01 styles, that is, there is no support for the legal extensions of CSL used e.g., in the Juris-M CSL styles (see https://juris-m.github.io/downloads/).  As for referencing previous footnotes, CSL 1.01 has only very rudimentary support for this: one can define note-based styles that give the full reference only in the note at the first mention of the source and later use only a short form and refer back to the note number of the full reference. There are a number of CSL styles using this functionality, e.g.  the CSL style "Journal of international economic law". The bottom line is that you can refer automatically only to the number of the note in which the first reference to the item in question appeared.

**Comment by ertwro** [comment]
I see. Thank you.
