### ISSUE TITLE
add to MELPA

### ISSUE THREAD

**Issue by titaniumbones** [andras-simonyi/citeproc-orgref#7]
Hi Andreas,
I think it would be great to have this on MELPA -- probably most people using citeproc-el also want to use the org extension.  I can see you're not actively developing right now, but this is a significant improvement as-is, so it seems worth just making it more pubicly accessible?

**Comment by andras-simonyi** [comment]
Hi, thanks for the suggestion! I have been planning to do this for a while, and will definitely do it sometime in this calendar year.  I wanted to add some tests before submission but if I can't find the time then will submit "as is".

**Comment by bdarcus** [comment]
Just bumping this ;-)

**Comment by andras-simonyi** [comment]
For the record: I've now opened a [pull request](https://github.com/melpa/melpa/pull/6959) to add citeproc-org to MELPA, hopefully it will be merged shortly.

**Comment by andras-simonyi** [comment]
citeproc-org is now available in MELPA (see commit https://github.com/melpa/melpa/commit/2055da5d0628ca3c35b111b5ded56c0f635ca690), so I'm closing this issue. (And thanks for for nudging me on this :-) )
