### ISSUE TITLE
org syntax question

### ISSUE THREAD

**Issue by bdarcus** [andras-simonyi/citeproc-orgref#8]
I was wondering if you could clarify the current citation syntax for me (before I sign up for the org list and engage there), and if any of this is relevant, update the documentation accordingly?

The short form, can only have the single citekey, and nothing else? No multiple citations, and no locators? 

I couldn't, for example, do something like `[@doe19, p.12]`?

From your docs I am assuming no, and one would need to use the more complex and verbose syntax.

I don't understand, I guess, why this from pandoc wouldn't work.

https://pandoc.org/org.html#simple-citation

**Comment by andras-simonyi** [comment]
I've checked now with the current state of the wip-cite branch and it still seems to be the case that the short form can contain only a single cite key, nothing else. Note that the branch has not been updated for a year now  so it is totally outdated, not in sync with recent Org versions. Unfortunately, the _de facto_ citation syntax for Org is org-ref's cite links, which I personally find rather cumbersome.

**Comment by bdarcus** [comment]
Do you have any thoughts on how to move this all forward?

I created CSL, and helped develop the syntax for pandoc, but am not super knowledge about emacs and org tech and community.

**Comment by bdarcus** [comment]
I posted on the org list to try to get this conversation going again.

https://lists.gnu.org/archive/html/emacs-orgmode/2020-04/msg00100.html

**Comment by tarleb** [comment]
Just commenting to be left in the loop.
I'm the maintainer of pandoc's org-mode system.

**Comment by andras-simonyi** [comment]
Hi, apologies for reacting that late, and thanks a lot  for reinvigorating the citation syntax discussion on the org-mode mailing list! Should I keep this issue open for further discussion?

**Comment by bdarcus** [comment]
Totally up to you. I'm happy with how things are evolving on the org front.

**Comment by andras-simonyi** [comment]
Thanks, in that case I'll close it after a few days of inactivity.

**Comment by bdarcus** [comment]
I'll just add that hopefully they get back to you soon on your questions. Integrating your code would make it easier and quicker to address a variety of details. One of them I was just, this minute, thinking about: citation locators.

**Comment by andras-simonyi** [comment]
As for integration, I looked a bit more into this and unfortunately it would probably require a huge amount of rewriting without any functionality benefits, as Emacs does not contain some very popular libraries that my code uses. See, e.g., the discussion about the s string manipulation library [here](https://github.com/magnars/s.el/issues/136).  Maybe it'd be a better solution after all to implement something very basic as a built-in citation renderer and keep citeproc-el and a citeproc-el based exporter add-on as separate packages. But, of course, let's see how the discussion on the Org mailing list unfolds. 

Locators: Yes it also occurred to me that this part of the syntax should  be clarified as well. It seems that a large part of the existing Emacs citation infrastructure (e.g., org-ref) simply ignores the fact that cites can contain locators. I guess the main reason is that most of the developers and users have a STEM background where locators are not so important as in the humanities.

**Comment by bdarcus** [comment]
> As for integration, I looked a bit more into this and unfortunately it would probably require a huge amount of rewriting without any functionality benefits, as Emacs does not contain some very popular libraries that my code uses. See, e.g., the discussion about the s string manipulation library [here](https://github.com/magnars/s.el/issues/136). Maybe it'd be a better solution after all to implement something very basic as a built-in citation renderer and keep citeproc-el and a citeproc-el based exporter add-on as separate packages. But, of course, let's see how the discussion on the Org mailing list unfolds.

It seems if the functionality is designed right, the only difference would be needing to install your package.
 
> Locators: Yes it also occurred to me that this part of the syntax should be clarified as well. It seems that a large part of the existing Emacs citation infrastructure (e.g., org-ref) simply ignores the fact that cites can contain locators. I guess the main reason is that most of the developers and users have a STEM background where locators are not so important as in the humanities.

Yes, I'm sure that's right.

Presumably including some basic rules for parsing the post string, as you have, and as pandoc has, would be enough.
