### ISSUE TITLE
html export fails for bibtex entries with unicode character 

### ISSUE THREAD

**Issue by cryoguy** [andras-simonyi/citeproc-orgref#9]
html export failed with the following error:
`replace-regexp-in-string:` Wrong type argument: stringp, (ly-raw string `"\"æ\"")`

 It turns out to be one of my bibtex entry with "æ" in the abstract section. 

 org-ref WORKS.

**Comment by andras-simonyi** [comment]
Thanks for reporting this. Although "abstract" is actually not a valid BibTeX field and is therefore unsupported, there was indeed a bug in the citeproc-el library (which citeproc-org uses for BibTeX parsing) which caused an error when a field contained the "\ae" LaTeX command. I've made some changes in citeproc-el which hopefully solves the problem. Could you update your version of the citeproc package from MELPA unstable and report back whether the change resolved the issue?

**Comment by asimonyi** [comment]
If you have no objections I'll go on and close this issue as fixed.

**Comment by andras-simonyi** [comment]
If you have no objections then I'll close this issue as fixed shortly.
